### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by ekkis** [scf2k/karma-jquery#2]
I followed the easy instructions on the main page but when my source runs I get the error:

> PhantomJS 1.9.8 (Mac OS X 0.0.0) ERROR
>  ReferenceError: Can't find variable: $
>  at /Users/ekkis/Downloads/client-side-testing/test/tests.js:18104

which means that jquery didn't get included.  I've seen somewhere that karma can make global variables available... how is it done?

**Comment by scf2k** [comment]
Works with such config

```
module.exports = function(config) {
  config.set({
    plugins: ['karma-jquery', 'karma-firefox-launcher', 'karma-jasmine'],
    frameworks: ['jquery-1.8.3', 'jasmine'],
    files:['file.js'],
    browsers : ['Firefox']
})};
```
